name: 'SpawnerControl'
version: '${project.version}'
main: 'me.stumper66.spawnercontrol.SpawnerControl'
softdepend: [ 'WorldGuard' ]
api-version: '1.13'
author: 'stumper66'
description: '${project.description}'
website: 'https://github.com/stumper66/SlimeSpawners'

commands:
  spawnercontrol:
    description: 'Manage SpawnerControl'
    aliases: [ 'sc' ]
    usage: '/<command> <debug>|<reload>|<info>|<spawners>|<enable>|<disable>|<label>'